In [106]:
import numpy as np

## NumPy arrays

Creating arrays

* `np.zeros`
* `np.ones`
* `np.full`
* `np.repeat`
* `np.array`
* `np.arange`

In [107]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [108]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [109]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [111]:
a = np.array([1,2 ,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [112]:
a.shape

(6,)

In [113]:
np.arange(3, 10, 0.2)


array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4,
       5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ,
       8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [114]:
array = np.repeat(0.0, 10) 
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [116]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

Accessing the element of an array by index:

In [117]:
el = array[1]
print(el)

0.0


Accessing multuple elements of an array by a list of indices:

In [118]:
array[[4, 2, 0]]

array([1., 1., 0.])

Assignment:

In [119]:
array[1] = 1
print(array)

[0. 1. 1. 1. 1.]


Creating an array from a list with integers:

In [120]:
elements = [1, 2, 3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

Specifying the type of elements:

In [121]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

`np.arange` for creating ranges:

In [122]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


Linspace - for creating an array with elements from `start` till `end` of a certain size: 

In [123]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [124]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

Be careful with overflowing:

In [125]:
zeros[0] = 300
zeros

/tmp/ipykernel_5879/1640675828.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  zeros[0] = 300


array([44,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8)

In [126]:
zeros[0] = 300
print(zeros[0])

44


/tmp/ipykernel_5879/2020449431.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  zeros[0] = 300


In [127]:
300 % 256

44

## Multi-dimensional NumPy arrays

Specify the shape with a tuple:

In [128]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [129]:
print(zeros.shape)

(5, 2)


In [130]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [131]:
numbers.shape

(3, 3)

In [132]:
print(numbers[0, 1])

2


Assignment: use a tuple (row index, column index)

In [133]:
numbers[0, 1] = 10

In [134]:
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [135]:
numbers[0]

array([ 1, 10,  3])

Slicing: getting a column:

In [136]:
numbers[:, 1]

array([10,  5,  8])

In [137]:
numbers[1, :] == [4, 5, 6]

array([ True,  True,  True])

In [138]:
numbers[0 : 2, 0:2] 

array([[ 1, 10],
       [ 4,  5]])

Assigning a row:

In [139]:
numbers[1] = [1, 1, 1]

In [140]:
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

Assigning a column:

In [141]:
numbers[:, 2] = [9, 9, 9]

In [142]:
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

## Randomly generated arrays


Uniform random numbers between 0 and 1 of shape (5, 2):

In [143]:
np.random.rand(5, 2)

array([[0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863],
       [0.61927097, 0.29965467],
       [0.26682728, 0.62113383],
       [0.52914209, 0.13457995]])

Set seed for reproducibility:

In [144]:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [145]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Random integers between 0 and 99 (100 is not included)

In [146]:
np.random.seed(2)
np.random.randint(low=0, high = 1000, size=(5, 2))

array([[168, 527],
       [493, 584],
       [534, 299],
       [466,  75],
       [360, 263]])

## Element-wise operations

In [147]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

Every item in the array is multiplied by 2:

In [148]:
rng * 2

array([0, 2, 4, 6, 8])

In [149]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

Adding one array with another

In [150]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [151]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [152]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

Rounding the numbers to 4th digit:

In [153]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

Two ways to square each element:

* element-wise multiplication with itself
* the power operator (`**`)

In [154]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [155]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [156]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

Other element-wise operations:

- `exp`
- `log`
- `sqrt`

In [157]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [158]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [159]:
np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

### Comparison operations

In [160]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [161]:
result = pred >= 0.5
result

array([False, False,  True])

In [162]:
np.random.seed(2)


In [163]:
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [164]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [165]:
pred1 >= pred2

array([ True, False,  True])

In [166]:
np.random.seed(2)

In [167]:
pred1 = np.random.rand(3) >= 0.3
pred1

array([ True, False,  True])

In [168]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True,  True, False])

### Logical operations

In [169]:
pred1 & pred2

array([ True, False, False])

In [170]:
pred1 | pred2

array([ True,  True,  True])

## Summarizing operations

Summarizing operations process and array and return a single number 

In [171]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [172]:
pred_sum

1.02

In [173]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


For two-dimentional array it works in the same way:

In [174]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [175]:
matrix.max()

0.62

But we can specify the axis along which we apply the summarizing operation

- `axis=1` - apply to each rows
- `axis=0` - apply to each column

In [176]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [177]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [178]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

## Sorting

In [180]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

Creaters a new array:

In [181]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [182]:
pred

array([0.44, 0.03, 0.55, 0.44])

Sorts in place:

In [183]:
pred.sort()

In [184]:
pred

array([0.03, 0.44, 0.44, 0.55])

Argsort - instead of sorting, return the indexes of the array in sorted order

In [185]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [186]:
idx = pred.argsort()

In [187]:
idx

array([1, 0, 3, 2])

In [188]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

## Reshaping

The shape of an array cound be changed

In [75]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
rng.shape

(12,)

In [77]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

But number of rows x columns should be equal to the total number of elements

In [79]:
rng.reshape(4, 4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [80]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [81]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

Putting mulitple arrays together:

- `concatenate`
- `hstack`
- `vstack`
- `column_stack`

In [82]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [83]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [84]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [85]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [87]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [88]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [89]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [90]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

Transpose

In [91]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [92]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

## Slicing

Taking a part of the array

In [93]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [94]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [96]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [97]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [98]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [99]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [100]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

## Linear Algebra
### Multiplication

Vector-vector multiplication

In [101]:
u = np.array([0, 1, 2])
v = np.array([1, 2, 3])

u.dot(v)

8

Matrix-vector multiplication

In [102]:
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [103]:
X.dot(u)

array([5, 8, 9])

In [104]:
U = np.array([
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8]
])

In [105]:
X.dot(U)

array([[17, 20, 23],
       [32, 38, 44],
       [41, 49, 57]])

### Inverse

To inverse a matrix, use `inv` function from `linalg` package

In [106]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [107]:
Ainv = np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [108]:
A.dot(Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

B is not invertible ("singular"):

In [109]:
B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])

np.linalg.inv(B)

LinAlgError: Singular matrix

Note: When you need to solve _Ax = b_, you don't really to compute the inverse. You can use `solve`:

In [110]:
b = np.array([1, 2, 3])

In [111]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [112]:
A.dot(x)

array([1., 2., 3.])